### ISSUE TITLE
Verify if email adresses listes on receiver list on wiki.glidernet.org exist

### ISSUE THREAD

**Issue by dspreitz** [kerel-fs/ogn-rdb#1]
Kerel,
I understand, that you want to check if there is a way to contact the ogn station operators in case of problems. This is a way to judge, if a ogn station is trustworthy.
At the moment you script does not check if there is a valid e-mail adress associated to a ogn-station entry.
Do you think checking for a valid e-mail would be worth wile?
https://www.webdigi.co.uk/blog/2009/how-to-check-if-an-email-address-exists-without-sending-an-email/

Dominic

**Comment by kerel-fs** [comment]
59f4c8c7d60290b4f99532b0d6df2b3a7847f9fa introduced a very simple, regexp-based email address verification.
Checking the existence of the domain/the mailbox does not verify a station operator
since it's possible to insert foreign email addresses.
(For now) the ogn-rdb is just a pretty frontend for the list-of-receivers in the wiki so I would rather not implement such a check.
