### ISSUE TITLE
Cron script missing

### ISSUE THREAD

**Issue by pyrog** [kerel-fs/ogn-rdb#7]
Local files are missing:
* glidern1/status.json
* glidern2/status.json
* glidern3/status.json

A "cron script" that run [mkreceiverjson.py](https://github.com/kerel-fs/ogn-rdb/blob/master/mkreceiverjson.py) each hours is missing.
The server probably cache theses files, but an how ?

Last but not least, [web/js/controllers.js](https://github.com/kerel-fs/ogn-rdb/blob/master/web/js/controllers.js) use the copies on [ogn.peanutpod.de](https://ogn.peanutpod.de/glidern1/status.json), not the local copies on the project.

**Comment by kerel-fs** [comment]
1. The status.json files are proxied by ogn.peanutpod.de so there is no local copy. This is done by nginx,
configured via [ansible](https://ansible.com).
2. The cron script is included in my local ansible-playbook. I thought it's from less interest so I didn't publish it by now. If there is interest in it, I will publish it.
3. This is intentional to minimize the load on the arps servers (caching) and to serve all content by the same origin.

edit: Updated answer nr.3, misunderstood your comment.
old answer: This is intentional. The webserver gets manually updated by an ansible-playbook run.
